[theme]
primaryColor="#2E8B57"
backgroundColor="#F8F9FA"
secondaryBackgroundColor="#FFFFFF"
textColor="#000000"
font="sans serif"

[server]
headless=true
runOnSave=false
port=10000
fileWatcherType="none"
enableWebsocketCompression=false

[browser]
serverAddress="multilingual-aitribalchatbot.onrender.com"
serverPort=10000
gatherUsageStats=false